/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Troca a API key por um token de aplicação
     * @description Emite o token que a aplicação usa em `POST /logs` (RN-16).
     *
     *     - Exige API key válida (RN-02) e cliente ativo (RN-03).
     *     - Validade de 1 hora, nunca além da expiração da API key: `exp = min(iat + 3600 s, expires_at da chave)`.
     *     - Não existe renovação: perto de expirar, a aplicação pede outro token. Uma aplicação pode ter vários tokens válidos ao mesmo tempo.
     *     - O token não é gravado. Revogar a API key impede novos tokens, mas os já emitidos valem até expirar.
     */
    post: operations['issueApplicationToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login do usuário no painel (proposta)
     * @description **Proposta.** Troca e-mail e senha por um token de usuário, usado nas rotas do painel.
     *
     *     - Mesmas regras do token de aplicação: JWT HS256, validade de 1 hora, sem renovação, não é gravado.
     *     - O token de usuário não é aceito em `POST /logs`, e o de aplicação não é aceito no painel.
     *     - E-mail inexistente e senha errada dão a mesma resposta 401, para não revelar quais e-mails existem.
     *     - Usuário de cliente inativo recebe 403.
     */
    post: operations['issueUserToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lista os logs do cliente (proposta)
     * @description **Proposta.** Lista os logs do cliente do usuário, mais recentes primeiro (`occurred_at` decrescente).
     *
     *     - Só logs do cliente do usuário (RN-09). Não existe parâmetro de cliente.
     *     - Os filtros se combinam com E. Repetir `tags` retorna os logs que têm todas as tags.
     *     - Paginação por cursor: passe o `next_cursor` da resposta em `cursor` até ele vir `null`.
     */
    get: operations['listLogs'];
    put?: never;
    /**
     * Envia um log
     * @description Grava um log da aplicação dona do token.
     *
     *     - Cliente e aplicação vêm do token, nunca do corpo: `customer_id` no corpo → 422 e nada é gravado (RN-01).
     *     - A API preenche `id`, `application_id`, `application_name`, `received_at`, `expire_at` e a lista final de `tags` (RN-07).
     *     - Campos sensíveis de `information_data`, como `password` e `cpf`, são mascarados antes de gravar (RN-06).
     *     - Tags gravadas: as da aplicação somadas às do log. Numa chave que a aplicação já define, vale a da aplicação (RN-15).
     *     - `expire_at = received_at + retention_days` do cliente; depois dessa data o log é apagado (RN-08).
     *
     *     Ordem das checagens: token (401) → cliente ativo (403) → corpo e tags (422) →
     *     tamanho e chaves de `information_data` (413 ou 422) → gravação (201).
     */
    post: operations['createLog'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs/{log_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalhe de um log (proposta)
     * @description **Proposta.** Um log do cliente do usuário. Log de outro cliente responde 404 (RN-09).
     */
    get: operations['getLog'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/applications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lista as aplicações do cliente (proposta)
     * @description **Proposta.** Todas as aplicações do cliente do usuário, com as suas API keys (sem o hash).
     */
    get: operations['listApplications'];
    put?: never;
    /**
     * Cadastra uma aplicação (proposta)
     * @description **Proposta.** Cadastra uma aplicação no cliente do usuário (RN-13). A aplicação nasce sem API keys:
     *     crie uma em `POST /applications/{application_id}/api-keys`.
     *
     *     O nome é único dentro do cliente, sem diferenciar maiúsculas de minúsculas: "Checkout" e "checkout"
     *     são a mesma aplicação → 409.
     */
    post: operations['createApplication'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/applications/{application_id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id da aplicação. */
        application_id: components['parameters']['ApplicationId'];
      };
      cookie?: never;
    };
    /**
     * Detalhe de uma aplicação (proposta)
     * @description **Proposta.** Uma aplicação do cliente do usuário, com as suas API keys (sem o hash).
     */
    get: operations['getApplication'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Altera o nome ou as tags de uma aplicação (proposta)
     * @description **Proposta.** Altera só os campos enviados. `tags` substitui a lista inteira.
     *
     *     Logs já gravados não mudam: o nome e as tags foram copiados neles na ingestão (ADR-003, ADR-015).
     */
    patch: operations['updateApplication'];
    trace?: never;
  };
  '/applications/{application_id}/api-keys': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id da aplicação. */
        application_id: components['parameters']['ApplicationId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Gera uma API key para a aplicação (proposta)
     * @description **Proposta.** Gera uma API key nova (RN-12, ADR-008).
     *
     *     - A chave completa (`key`) aparece só nesta resposta. O banco guarda só o hash e o prefixo.
     *     - A aplicação pode ter várias chaves; cada uma expira ou é revogada sem afetar as outras.
     *     - Sem `expires_at`, a chave não expira.
     */
    post: operations['createApiKey'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/applications/{application_id}/api-keys/{prefix}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id da aplicação. */
        application_id: components['parameters']['ApplicationId'];
        /** @description Prefixo da API key, que a identifica dentro da aplicação. */
        prefix: components['parameters']['ApiKeyPrefix'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoga uma API key (proposta)
     * @description **Proposta.** Revoga a chave: ela deixa de emitir tokens na hora (RN-02). Os tokens já emitidos
     *     com ela continuam válidos até expirar, no máximo 1 hora (RN-16).
     *
     *     Idempotente: revogar uma chave já revogada devolve 200 com o `revoked_at` original.
     */
    post: operations['revokeApiKey'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lista os usuários do cliente (proposta)
     * @description **Proposta.** Todos os usuários do cliente do usuário logado.
     */
    get: operations['listUsers'];
    put?: never;
    /**
     * Cadastra um usuário no cliente (proposta)
     * @description **Proposta.** Cadastra um usuário no cliente do usuário logado (RN-11).
     *
     *     - O e-mail é único em toda a plataforma, sem diferenciar maiúsculas de minúsculas: e-mail já cadastrado → 409.
     *     - A senha é guardada só como hash (pwdlib + Argon2) e nunca volta nas respostas.
     */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Usuário logado (proposta)
     * @description **Proposta.** O usuário dono do token.
     */
    get: operations['getCurrentUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Detalhe de um usuário (proposta)
     * @description **Proposta.** Um usuário do cliente do usuário logado. Usuário de outro cliente responde 404.
     */
    get: operations['getUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cadastra uma empresa cliente e o seu primeiro usuário (proposta)
     * @description **Proposta.** Cadastro de uma empresa nova na plataforma, junto com o primeiro usuário, que depois
     *     faz login em `POST /auth/login`. O cliente nasce ativo (`is_active: true`).
     *
     *     E-mail do usuário já cadastrado → 409, e nada é gravado.
     */
    post: operations['registerCustomer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/customers/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cliente do usuário logado (proposta)
     * @description **Proposta.** O cliente ao qual o usuário logado pertence.
     */
    get: operations['getCurrentCustomer'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Altera o nome ou a retenção do cliente (proposta)
     * @description **Proposta.** Altera só os campos enviados.
     *
     *     Um `retention_days` novo vale só para os logs recebidos depois da mudança: o `expire_at` de cada log
     *     é calculado na gravação e não muda (ADR-004). `is_active` não é alterado por esta API.
     */
    patch: operations['updateCurrentCustomer'];
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Saúde da API e do MongoDB
     * @description Faz um `ping` no MongoDB. É o healthcheck do container da API.
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Id no formato `ObjectId` do MongoDB, em texto.
     * @example 66f8a1c2e4b0a1b2c3d4e5f6
     */
    ObjectId: string;
    /**
     * @description Severidade do log, gravada como número (ADR-011).
     *
     *     | Valor | Nome |
     *     |---|---|
     *     | 0 | TRACE |
     *     | 1 | DEBUG |
     *     | 2 | INFORMATION |
     *     | 3 | WARNING |
     *     | 4 | ERROR |
     *     | 5 | CRITICAL |
     * @example 4
     * @enum {integer}
     */
    LogLevel: 0 | 1 | 2 | 3 | 4 | 5;
    /**
     * @description Tag no formato `chave:valor`, separados pelo primeiro `:` (RN-15).
     *
     *     A API remove os espaços das pontas e converte para minúsculas antes de validar: `" Feature:PIX"`
     *     vira `feature:pix`. Depois disso, a chave só tem letras minúsculas, dígitos, `_` e `-`; o valor
     *     não é vazio nem tem espaços; a tag tem até 100 caracteres. Fora disso → 422.
     *
     *     Tags não são mascaradas e ficam indexadas: nunca coloque dado pessoal numa tag.
     * @example feature:pix
     */
    TagInput: string;
    /** @description Até 20 tags. Repetidas, depois de normalizadas, são descartadas. */
    TagListInput: components['schemas']['TagInput'][];
    /**
     * @description Tag normalizada, `chave:valor` em minúsculas.
     * @example team:checkout
     */
    Tag: string;
    /** @description O log como a aplicação envia. Campos desconhecidos, como `customer_id`, são recusados com 422. */
    LogCreate: {
      /**
       * Format: uuid
       * @description Liga os logs de um mesmo fluxo.
       */
      correlation_id?: string | null;
      level: components['schemas']['LogLevel'];
      message: string;
      /** @description Tipo, mensagem ou stack trace da exceção, quando houver. */
      exception?: string | null;
      /** @example production */
      environment: string;
      /**
       * @description O objeto que a aplicação estava manipulando, livre (RN-05, RN-06).
       *
       *     - Tamanho máximo: 64 KB (valor em aberto). Acima disso → 413.
       *     - Chaves com `$` ou `.`, em qualquer nível, são recusadas com 422 (ex.: `$where`, `a.b`).
       *     - Campos sensíveis, como `password` e `cpf`, são mascarados antes de gravar.
       */
      information_data?: {
        [key: string]: unknown;
      } | null;
      /**
       * @description Tags deste log. Somadas às da aplicação na gravação; numa chave que a aplicação já define, vale a da aplicação.
       * @default []
       */
      tags: components['schemas']['TagListInput'];
      /**
       * Format: date-time
       * @description Quando o evento aconteceu na aplicação, com fuso.
       */
      occurred_at: string;
    };
    /** @description O log como a API devolve. */
    LogRead: {
      id: components['schemas']['ObjectId'];
      application_id: components['schemas']['ObjectId'];
      /** @description Nome da aplicação quando o log foi gravado. */
      application_name: string;
      /** Format: uuid */
      correlation_id: string | null;
      level: components['schemas']['LogLevel'];
      message: string;
      exception: string | null;
      environment: string;
      /** @description Com os campos sensíveis já mascarados. */
      information_data: {
        [key: string]: unknown;
      } | null;
      /** @description Lista final, com as tags da aplicação somadas às do log. */
      tags: components['schemas']['Tag'][];
      /**
       * Format: date-time
       * @description Quando o evento aconteceu na aplicação.
       */
      occurred_at: string;
      /**
       * Format: date-time
       * @description Quando o log chegou à API.
       */
      received_at: string;
      /**
       * Format: date-time
       * @description Depois desta data o log é apagado. É `received_at` somado ao `retention_days` do cliente.
       */
      expire_at: string;
    };
    LogPage: {
      items: components['schemas']['LogRead'][];
      /** @description Cursor da próxima página. `null` quando não há mais logs. */
      next_cursor: string | null;
    };
    /** @description Nomes do OAuth 2.0. */
    TokenResponse: {
      /** @description JWT assinado com HS256. */
      access_token: string;
      /** @enum {string} */
      token_type: 'bearer';
      /** @description Segundos até o token expirar. Menor que 3600 quando a API key expira antes de 1 hora. */
      expires_in: number;
    };
    UserLogin: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    ApplicationCreate: {
      /** @description Único dentro do cliente, sem diferenciar maiúsculas de minúsculas. */
      name: string;
      /**
       * @description Tags que valem para todos os logs da aplicação.
       * @default []
       */
      tags: components['schemas']['TagListInput'];
    };
    ApplicationUpdate: {
      name?: string;
      /** @description Substitui a lista inteira. Não altera os logs já gravados. */
      tags?: components['schemas']['TagListInput'];
    };
    ApplicationRead: {
      id: components['schemas']['ObjectId'];
      name: string;
      tags: components['schemas']['Tag'][];
      api_keys: components['schemas']['ApiKeyRead'][];
      /** Format: date-time */
      created_at: string;
    };
    ApplicationList: {
      items: components['schemas']['ApplicationRead'][];
    };
    ApiKeyCreate: {
      /**
       * Format: date-time
       * @description Precisa estar no futuro. Sem valor, a chave não expira.
       */
      expires_at?: string | null;
    };
    /** @description API key sem o segredo. O hash nunca sai da API. */
    ApiKeyRead: {
      /**
       * @description Prefixo curto que identifica a chave.
       * @example lx_ab12
       */
      prefix: string;
      /** Format: date-time */
      expires_at: string | null;
      /** Format: date-time */
      revoked_at: string | null;
    };
    /** @description API key recém-gerada, com o segredo. */
    ApiKeyCreated: components['schemas']['ApiKeyRead'] & {
      /** @description A chave completa. Aparece só nesta resposta; guarde-a em lugar seguro. */
      key: string;
    };
    UserCreate: {
      name: string;
      /**
       * Format: email
       * @description Único em toda a plataforma, sem diferenciar maiúsculas de minúsculas.
       */
      email: string;
      /** Format: password */
      password: string;
    };
    UserRead: {
      id: components['schemas']['ObjectId'];
      name: string;
      /** Format: email */
      email: string;
      /** Format: date-time */
      created_at: string;
    };
    UserList: {
      items: components['schemas']['UserRead'][];
    };
    CustomerCreate: {
      name: string;
      /** @description Por quantos dias os logs do cliente ficam guardados (RN-08). Até 3650 dias (10 anos). */
      retention_days: number;
    };
    CustomerRegistration: {
      customer: components['schemas']['CustomerCreate'];
      user: components['schemas']['UserCreate'];
    };
    CustomerRegistrationResult: {
      customer: components['schemas']['CustomerRead'];
      user: components['schemas']['UserRead'];
    };
    CustomerUpdate: {
      name?: string;
      /** @description Vale só para os logs recebidos depois da mudança. Até 3650 dias (10 anos). */
      retention_days?: number;
    };
    CustomerRead: {
      id: components['schemas']['ObjectId'];
      name: string;
      is_active: boolean;
      retention_days: number;
      /** Format: date-time */
      created_at: string;
    };
    Health: {
      /** @enum {string} */
      status: 'ok' | 'unavailable';
      /** @enum {string} */
      mongodb: 'up' | 'down';
    };
    /** @description Erro no formato Problem Details (RFC 9457). */
    Problem: {
      /**
       * Format: uri-reference
       * @default about:blank
       */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** Format: uri-reference */
      instance?: string;
    };
    /** @description Problem Details com a lista de campos inválidos, no formato dos erros do Pydantic. */
    ValidationProblem: components['schemas']['Problem'] & {
      errors: {
        /** @description Caminho do campo, ex.: `["body", "tags", 0]`. */
        loc: (string | number)[];
        msg: string;
        type: string;
      }[];
    };
  };
  responses: {
    /** @description API key ausente, inexistente, expirada ou revogada (RN-02). */
    InvalidApiKey: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Unauthorized",
         *       "status": 401,
         *       "detail": "API key ausente, inválida, expirada ou revogada."
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description E-mail ou senha incorretos. */
    InvalidCredentials: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Unauthorized",
         *       "status": 401,
         *       "detail": "E-mail ou senha incorretos."
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Token ausente, inválido ou expirado, ou token do tipo errado para a rota. */
    InvalidBearerToken: {
      headers: {
        'WWW-Authenticate': components['headers']['WwwAuthenticateBearer'];
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Unauthorized",
         *       "status": 401,
         *       "detail": "Token ausente, inválido ou expirado."
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description O cliente dono da credencial está inativo (RN-03). */
    CustomerInactive: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Forbidden",
         *       "status": 403,
         *       "detail": "O cliente está inativo."
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description O recurso não existe ou é de outro cliente (RN-09). */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Not Found",
         *       "status": 404,
         *       "detail": "Recurso não encontrado."
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Viola uma regra de unicidade, como e-mail de usuário ou nome de aplicação já cadastrados. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Conflict",
         *       "status": 409,
         *       "detail": "Já existe um usuário com este e-mail."
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description `information_data` acima do limite de tamanho (RN-05). */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Content Too Large",
         *       "status": 413,
         *       "detail": "information_data passa do limite de 64 KB."
         *     }
         */
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Corpo ou parâmetro inválido, campo desconhecido ou regra de formato violada. */
    ValidationFailed: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "type": "about:blank",
         *       "title": "Unprocessable Content",
         *       "status": 422,
         *       "detail": "A requisição tem campos inválidos.",
         *       "errors": [
         *         {
         *           "loc": [
         *             "body",
         *             "customer_id"
         *           ],
         *           "msg": "Extra inputs are not permitted",
         *           "type": "extra_forbidden"
         *         },
         *         {
         *           "loc": [
         *             "body",
         *             "tags",
         *             0
         *           ],
         *           "msg": "A tag precisa estar no formato chave:valor.",
         *           "type": "value_error"
         *         }
         *       ]
         *     }
         */
        'application/problem+json': components['schemas']['ValidationProblem'];
      };
    };
  };
  parameters: {
    /** @description Id da aplicação. */
    ApplicationId: components['schemas']['ObjectId'];
    /** @description Prefixo da API key, que a identifica dentro da aplicação. */
    ApiKeyPrefix: string;
    /** @description Id do log. */
    LogId: components['schemas']['ObjectId'];
    /** @description Id do usuário. */
    UserId: components['schemas']['ObjectId'];
  };
  requestBodies: never;
  headers: {
    /** @description Caminho do recurso criado. */
    Location: string;
    /** @description A resposta traz uma credencial e não pode ficar em cache. */
    CacheControlNoStore: 'no-store';
    /** @description Indica que a rota espera um token Bearer. */
    WwwAuthenticateBearer: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  issueApplicationToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token emitido. */
      200: {
        headers: {
          'Cache-Control': components['headers']['CacheControlNoStore'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmY4YTFjMmU0YjBhMWIyYzNkNGU1ZjYifQ.sig",
           *       "token_type": "bearer",
           *       "expires_in": 3600
           *     }
           */
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      401: components['responses']['InvalidApiKey'];
      403: components['responses']['CustomerInactive'];
    };
  };
  issueUserToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "email": "ana@example.com",
         *       "password": "uma-senha-longa"
         *     }
         */
        'application/json': components['schemas']['UserLogin'];
      };
    };
    responses: {
      /** @description Token emitido. */
      200: {
        headers: {
          'Cache-Control': components['headers']['CacheControlNoStore'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmY4YjExMmU0YjBhMWIyYzNkNGU1ZjgifQ.sig",
           *       "token_type": "bearer",
           *       "expires_in": 3600
           *     }
           */
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      401: components['responses']['InvalidCredentials'];
      403: components['responses']['CustomerInactive'];
      422: components['responses']['ValidationFailed'];
    };
  };
  listLogs: {
    parameters: {
      query?: {
        /** @description Só logs desta aplicação. */
        application_id?: components['schemas']['ObjectId'];
        /** @description Só logs a partir deste nível, inclusive (RN-14). Ex.: `3` traz Warning, Error e Critical. */
        min_level?: components['schemas']['LogLevel'];
        /** @description Só logs deste fluxo. */
        correlation_id?: string;
        /** @description Início do período, inclusive (`occurred_at >= occurred_from`). */
        occurred_from?: string;
        /** @description Fim do período, exclusivo (`occurred_at < occurred_to`). */
        occurred_to?: string;
        /** @description Tags que o log precisa ter, todas (E). Repetir o parâmetro: `?tags=team:checkout&tags=feature:pix`. Passam pela mesma normalização da ingestão. */
        tags?: components['schemas']['TagListInput'];
        /** @description Quantidade máxima de logs na página. */
        limit?: number;
        /** @description Valor de `next_cursor` da página anterior. Opaco para quem chama. */
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Uma página de logs. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogPage'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      422: components['responses']['ValidationFailed'];
    };
  };
  createLog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogCreate'];
      };
    };
    responses: {
      /** @description Log gravado. */
      201: {
        headers: {
          Location: components['headers']['Location'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      413: components['responses']['PayloadTooLarge'];
      422: components['responses']['ValidationFailed'];
    };
  };
  getLog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id do log. */
        log_id: components['parameters']['LogId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description O log. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      404: components['responses']['NotFound'];
    };
  };
  listApplications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aplicações do cliente. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationList'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
    };
  };
  createApplication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "name": "checkout",
         *       "tags": [
         *         "team:checkout"
         *       ]
         *     }
         */
        'application/json': components['schemas']['ApplicationCreate'];
      };
    };
    responses: {
      /** @description Aplicação cadastrada. */
      201: {
        headers: {
          Location: components['headers']['Location'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": "66f8a1c2e4b0a1b2c3d4e5f6",
           *       "name": "checkout",
           *       "tags": [
           *         "team:checkout"
           *       ],
           *       "api_keys": [],
           *       "created_at": "2026-09-29T13:40:00Z"
           *     }
           */
          'application/json': components['schemas']['ApplicationRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      409: components['responses']['Conflict'];
      422: components['responses']['ValidationFailed'];
    };
  };
  getApplication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id da aplicação. */
        application_id: components['parameters']['ApplicationId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A aplicação. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      404: components['responses']['NotFound'];
    };
  };
  updateApplication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id da aplicação. */
        application_id: components['parameters']['ApplicationId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "tags": [
         *         "team:payments"
         *       ]
         *     }
         */
        'application/json': components['schemas']['ApplicationUpdate'];
      };
    };
    responses: {
      /** @description Aplicação alterada. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      422: components['responses']['ValidationFailed'];
    };
  };
  createApiKey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id da aplicação. */
        application_id: components['parameters']['ApplicationId'];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        /**
         * @example {
         *       "expires_at": "2027-03-31T23:59:59Z"
         *     }
         */
        'application/json': components['schemas']['ApiKeyCreate'];
      };
    };
    responses: {
      /** @description API key gerada. */
      201: {
        headers: {
          'Cache-Control': components['headers']['CacheControlNoStore'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "key": "lx_ab12.4Qm9X2vTzP7sLk3Wc8RbN5yHd1FgJ6eA",
           *       "prefix": "lx_ab12",
           *       "expires_at": "2027-03-31T23:59:59Z",
           *       "revoked_at": null
           *     }
           */
          'application/json': components['schemas']['ApiKeyCreated'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationFailed'];
    };
  };
  revokeApiKey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id da aplicação. */
        application_id: components['parameters']['ApplicationId'];
        /** @description Prefixo da API key, que a identifica dentro da aplicação. */
        prefix: components['parameters']['ApiKeyPrefix'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chave revogada. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "prefix": "lx_ab12",
           *       "expires_at": "2027-03-31T23:59:59Z",
           *       "revoked_at": "2026-09-29T15:10:00Z"
           *     }
           */
          'application/json': components['schemas']['ApiKeyRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      404: components['responses']['NotFound'];
    };
  };
  listUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usuários do cliente. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserList'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "name": "Bruno Exemplo",
         *       "email": "bruno@example.com",
         *       "password": "outra-senha-longa"
         *     }
         */
        'application/json': components['schemas']['UserCreate'];
      };
    };
    responses: {
      /** @description Usuário cadastrado. */
      201: {
        headers: {
          Location: components['headers']['Location'];
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": "66f8b2a4e4b0a1b2c3d4e5f9",
           *       "name": "Bruno Exemplo",
           *       "email": "bruno@example.com",
           *       "created_at": "2026-09-29T13:50:00Z"
           *     }
           */
          'application/json': components['schemas']['UserRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      409: components['responses']['Conflict'];
      422: components['responses']['ValidationFailed'];
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description O usuário logado. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id do usuário. */
        user_id: components['parameters']['UserId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description O usuário. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      404: components['responses']['NotFound'];
    };
  };
  registerCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "customer": {
         *         "name": "Loja Exemplo",
         *         "retention_days": 30
         *       },
         *       "user": {
         *         "name": "Ana Exemplo",
         *         "email": "ana@example.com",
         *         "password": "uma-senha-longa"
         *       }
         *     }
         */
        'application/json': components['schemas']['CustomerRegistration'];
      };
    };
    responses: {
      /** @description Cliente e usuário cadastrados. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerRegistrationResult'];
        };
      };
      409: components['responses']['Conflict'];
      422: components['responses']['ValidationFailed'];
    };
  };
  getCurrentCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description O cliente. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
    };
  };
  updateCurrentCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "retention_days": 7
         *     }
         */
        'application/json': components['schemas']['CustomerUpdate'];
      };
    };
    responses: {
      /** @description Cliente alterado. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerRead'];
        };
      };
      401: components['responses']['InvalidBearerToken'];
      403: components['responses']['CustomerInactive'];
      422: components['responses']['ValidationFailed'];
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API e MongoDB no ar. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "ok",
           *       "mongodb": "up"
           *     }
           */
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description O MongoDB não respondeu em 3 segundos. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "unavailable",
           *       "mongodb": "down"
           *     }
           */
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
}
